corporate_intel:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5434
      user: intel_user
      password: lsZXGgU92KhK5VqR
      dbname: corporate_intel
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
