corporate_intel:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5436
      user: postgres
      password: postgres
      dbname: corporate_intel
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
