# Staging Environment Values Override
environment: staging

replicaCount: 2

image:
  tag: staging
  pullPolicy: Always

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

config:
  appEnv: staging
  debug: true
  logLevel: DEBUG
  workers: 2

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: staging-api.corporate-intel.example.com
      paths:
        - path: /
          pathType: Prefix
    - host: staging.corporate-intel.example.com
      paths:
        - path: /api
          pathType: Prefix
  tls:
    - secretName: staging-corporate-intel-tls
      hosts:
        - staging-api.corporate-intel.example.com
        - staging.corporate-intel.example.com

# Database configuration
postgresql:
  enabled: true
  auth:
    database: corporate_intel_staging
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m

redis:
  enabled: true
  master:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m

rabbitmq:
  enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

minio:
  enabled: true
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

# Monitoring
prometheus:
  enabled: true
  server:
    retention: "7d"

grafana:
  enabled: true
  adminPassword: "staging-password-change-me"

# Security
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Persistence
persistence:
  enabled: false  # Use ephemeral storage for staging

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
