apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-server:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  - name: PostgreSQL
    type: postgres
    url: postgres-service:5432
    database: corporate_intel
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1400
      timescaledb: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod']
        mappedTags: [{ key: 'service.name', value: 'service' }]

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance']
        mappedTags: [{ key: 'service.name', value: 'service' }]
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true

  - name: TimescaleDB
    type: postgres
    url: postgres-service:5432
    database: corporate_intel
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1400
      timescaledb: true
      timeColumn: "timestamp"
      metricColumn: "metric_name"
