# This is a template for Sealed Secrets
# Do NOT commit actual secrets to git
# Use: kubectl create secret generic corporate-intel-secrets --from-literal=... --dry-run=client -o yaml | kubeseal -o yaml > sealed-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: corporate-intel-secrets
  labels:
    app: corporate-intel
type: Opaque
stringData:
  # Database Credentials (managed by Vault)
  DB_USER: "VAULT:secret/data/corporate-intel/db#username"
  DB_PASSWORD: "VAULT:secret/data/corporate-intel/db#password"
  DATABASE_URL: "VAULT:secret/data/corporate-intel/db#url"

  # Redis Password
  REDIS_PASSWORD: "VAULT:secret/data/corporate-intel/redis#password"

  # RabbitMQ Credentials
  RABBITMQ_USER: "VAULT:secret/data/corporate-intel/rabbitmq#username"
  RABBITMQ_PASSWORD: "VAULT:secret/data/corporate-intel/rabbitmq#password"

  # MinIO/S3 Credentials
  MINIO_ACCESS_KEY: "VAULT:secret/data/corporate-intel/minio#access_key"
  MINIO_SECRET_KEY: "VAULT:secret/data/corporate-intel/minio#secret_key"
  AWS_ACCESS_KEY_ID: "VAULT:secret/data/corporate-intel/aws#access_key"
  AWS_SECRET_ACCESS_KEY: "VAULT:secret/data/corporate-intel/aws#secret_key"

  # JWT Secrets
  SECRET_KEY: "VAULT:secret/data/corporate-intel/jwt#secret_key"
  AUTH_SECRET_KEY: "VAULT:secret/data/corporate-intel/jwt#auth_secret"

  # API Keys
  OPENAI_API_KEY: "VAULT:secret/data/corporate-intel/apis#openai"
  ANTHROPIC_API_KEY: "VAULT:secret/data/corporate-intel/apis#anthropic"
  SERP_API_KEY: "VAULT:secret/data/corporate-intel/apis#serp"

  # External Services
  SENTRY_DSN: "VAULT:secret/data/corporate-intel/sentry#dsn"
  SLACK_WEBHOOK_URL: "VAULT:secret/data/corporate-intel/slack#webhook"
  PAGERDUTY_API_KEY: "VAULT:secret/data/corporate-intel/pagerduty#api_key"

  # Encryption Keys
  ENCRYPTION_KEY: "VAULT:secret/data/corporate-intel/encryption#key"
  DATA_ENCRYPTION_KEY: "VAULT:secret/data/corporate-intel/encryption#data_key"

  # OAuth/SSO
  OAUTH_CLIENT_ID: "VAULT:secret/data/corporate-intel/oauth#client_id"
  OAUTH_CLIENT_SECRET: "VAULT:secret/data/corporate-intel/oauth#client_secret"
  SAML_CERTIFICATE: "VAULT:secret/data/corporate-intel/saml#certificate"
  SAML_PRIVATE_KEY: "VAULT:secret/data/corporate-intel/saml#private_key"

---
# Example of using External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: corporate-intel-vault-secrets
  labels:
    app: corporate-intel
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: corporate-intel-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret/data/corporate-intel/db
  - extract:
      key: secret/data/corporate-intel/redis
  - extract:
      key: secret/data/corporate-intel/rabbitmq
  - extract:
      key: secret/data/corporate-intel/minio
  - extract:
      key: secret/data/corporate-intel/jwt
  - extract:
      key: secret/data/corporate-intel/apis
  - extract:
      key: secret/data/corporate-intel/encryption

---
# Vault SecretStore Configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  labels:
    app: corporate-intel
spec:
  provider:
    vault:
      server: "http://vault.vault-system.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "corporate-intel"
          serviceAccountRef:
            name: "corporate-intel-api"
