apiVersion: apps/v1
kind: Deployment
metadata:
  name: corporate-intel-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: ENVIRONMENT
          value: "staging"
