apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  tier: non-production

images:
- name: corporate-intel
  newName: corporate-intel
  newTag: staging

replicas:
- name: corporate-intel-api
  count: 2

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- ingress-patch.yaml

patchesJson6902:
- target:
    group: autoscaling
    version: v2
    kind: HorizontalPodAutoscaler
    name: corporate-intel-api-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 10

configMapGenerator:
- name: corporate-intel-config
  behavior: merge
  literals:
  - APP_ENV=staging
  - DEBUG=true
  - LOG_LEVEL=DEBUG
  - WORKERS=2
